name: Deno CI

on:
  push:
    branches: [ main ]
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest

    name: Deno ${{ matrix.deno-version }}
    strategy:
      matrix:
        deno-version: ["v1.7", "v1.8", "nightly"]
      fail-fast: false

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Use Deno ${{ matrix.deno-version }}
      uses: denolib/setup-deno@v2
      with:
        deno-version: ${{ matrix.deno-version }}

    - name: Check index.ts
      run: time deno cache --reload ./lib/index.ts

    - name: Run examples/ping.ts
      run: time ./examples/ping.ts docker.io

    - name: Test
      run: time deno test --allow-net ./test/*.ts
